#version: '3.8'

services:
  server:
    image: google-sheets-project
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/config
    networks:
      - spreadsheets-network

networks:
  spreadsheets-network:
    driver: bridge
