// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v4 "google.golang.org/api/sheets/v4"
)

// MockSheetUseCase is a mock of SheetUseCase interface.
type MockSheetUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSheetUseCaseMockRecorder
}

// MockSheetUseCaseMockRecorder is the mock recorder for MockSheetUseCase.
type MockSheetUseCaseMockRecorder struct {
	mock *MockSheetUseCase
}

// NewMockSheetUseCase creates a new mock instance.
func NewMockSheetUseCase(ctrl *gomock.Controller) *MockSheetUseCase {
	mock := &MockSheetUseCase{ctrl: ctrl}
	mock.recorder = &MockSheetUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSheetUseCase) EXPECT() *MockSheetUseCaseMockRecorder {
	return m.recorder
}

// BatchUpdate mocks base method.
func (m *MockSheetUseCase) BatchUpdate(ctx context.Context, sheetId string, jsonBody []byte) (*v4.BatchUpdateSpreadsheetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, sheetId, jsonBody)
	ret0, _ := ret[0].(*v4.BatchUpdateSpreadsheetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockSheetUseCaseMockRecorder) BatchUpdate(ctx, sheetId, jsonBody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockSheetUseCase)(nil).BatchUpdate), ctx, sheetId, jsonBody)
}

// Create mocks base method.
func (m *MockSheetUseCase) Create(ctx context.Context, jsonBody []byte) (*v4.Spreadsheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, jsonBody)
	ret0, _ := ret[0].(*v4.Spreadsheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSheetUseCaseMockRecorder) Create(ctx, jsonBody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSheetUseCase)(nil).Create), ctx, jsonBody)
}

// Delete mocks base method.
func (m *MockSheetUseCase) Delete(ctx context.Context, sheetId, param string, jsonBody []byte) (*v4.ClearValuesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sheetId, param, jsonBody)
	ret0, _ := ret[0].(*v4.ClearValuesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSheetUseCaseMockRecorder) Delete(ctx, sheetId, param, jsonBody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSheetUseCase)(nil).Delete), ctx, sheetId, param, jsonBody)
}

// Get mocks base method.
func (m *MockSheetUseCase) Get(ctx context.Context, sheetId, param string) ([][]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sheetId, param)
	ret0, _ := ret[0].([][]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSheetUseCaseMockRecorder) Get(ctx, sheetId, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSheetUseCase)(nil).Get), ctx, sheetId, param)
}
