// Code generated by MockGen. DO NOT EDIT.
// Source: sheetUsecase.go

// Package mock_sheetUsecase is a generated GoMock package.
package mock_sheetUsecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/mickey-mickser/google-sheets-project/pkg/models"
	sheetUsecase "github.com/mickey-mickser/google-sheets-project/pkg/usecase/sheets"
	drive "google.golang.org/api/drive/v3"
	sheets "google.golang.org/api/sheets/v4"
)

// MockPermissionSetter is a mock of PermissionSetter interface.
type MockPermissionSetter struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionSetterMockRecorder
}

// MockPermissionSetterMockRecorder is the mock recorder for MockPermissionSetter.
type MockPermissionSetterMockRecorder struct {
	mock *MockPermissionSetter
}

// NewMockPermissionSetter creates a new mock instance.
func NewMockPermissionSetter(ctrl *gomock.Controller) *MockPermissionSetter {
	mock := &MockPermissionSetter{ctrl: ctrl}
	mock.recorder = &MockPermissionSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionSetter) EXPECT() *MockPermissionSetterMockRecorder {
	return m.recorder
}

// SetPermission mocks base method.
func (m *MockPermissionSetter) SetPermission(ctx context.Context, sheetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPermission", ctx, sheetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPermission indicates an expected call of SetPermission.
func (mr *MockPermissionSetterMockRecorder) SetPermission(ctx, sheetID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPermission", reflect.TypeOf((*MockPermissionSetter)(nil).SetPermission), ctx, sheetID)
}

// MockSheetUseCase is a mock of SheetUseCase interface.
type MockSheetUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSheetUseCaseMockRecorder
}

// MockSheetUseCaseMockRecorder is the mock recorder for MockSheetUseCase.
type MockSheetUseCaseMockRecorder struct {
	mock *MockSheetUseCase
}

// NewMockSheetUseCase creates a new mock instance.
func NewMockSheetUseCase(ctrl *gomock.Controller) *MockSheetUseCase {
	mock := &MockSheetUseCase{ctrl: ctrl}
	mock.recorder = &MockSheetUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSheetUseCase) EXPECT() *MockSheetUseCaseMockRecorder {
	return m.recorder
}

// BatchUpdate mocks base method.
func (m *MockSheetUseCase) BatchUpdate(ctx context.Context, sheetId string, updates []models.UpdateRequest) (*sheets.BatchUpdateValuesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, sheetId, updates)
	ret0, _ := ret[0].(*sheets.BatchUpdateValuesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockSheetUseCaseMockRecorder) BatchUpdate(ctx, sheetId, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockSheetUseCase)(nil).BatchUpdate), ctx, sheetId, updates)
}

// Create mocks base method.
func (m *MockSheetUseCase) Create(ctx context.Context, body models.CreateRequest) (*sheets.Spreadsheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, body)
	ret0, _ := ret[0].(*sheets.Spreadsheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSheetUseCaseMockRecorder) Create(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSheetUseCase)(nil).Create), ctx, body)
}

// Delete mocks base method.
func (m *MockSheetUseCase) Delete(ctx context.Context, sheetId, param string) (*sheets.ClearValuesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sheetId, param)
	ret0, _ := ret[0].(*sheets.ClearValuesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSheetUseCaseMockRecorder) Delete(ctx, sheetId, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSheetUseCase)(nil).Delete), ctx, sheetId, param)
}

// Get mocks base method.
func (m *MockSheetUseCase) Get(ctx context.Context, sheetId, param string) ([][]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sheetId, param)
	ret0, _ := ret[0].([][]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSheetUseCaseMockRecorder) Get(ctx, sheetId, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSheetUseCase)(nil).Get), ctx, sheetId, param)
}

// SetPermissionSetter mocks base method.
func (m *MockSheetUseCase) SetPermissionSetter(ps sheetUsecase.PermissionSetter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPermissionSetter", ps)
}

// SetPermissionSetter indicates an expected call of SetPermissionSetter.
func (mr *MockSheetUseCaseMockRecorder) SetPermissionSetter(ps interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPermissionSetter", reflect.TypeOf((*MockSheetUseCase)(nil).SetPermissionSetter), ps)
}

// SharePermission mocks base method.
func (m *MockSheetUseCase) SharePermission(ctx context.Context, body models.ShareRequest) (*drive.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SharePermission", ctx, body)
	ret0, _ := ret[0].(*drive.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SharePermission indicates an expected call of SharePermission.
func (mr *MockSheetUseCaseMockRecorder) SharePermission(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SharePermission", reflect.TypeOf((*MockSheetUseCase)(nil).SharePermission), ctx, body)
}
